### ISSUE TITLE
Unhandled exception in update_all (possibly caused by disabled device)

### ISSUE THREAD

**Issue by islepnev** [wirenboard/wb-mcu-fw-updater#13]
update-all fails, but single device update is Ok.

It could be useful to increase verbosity in error message, i.e. print out port and address of problematic device.

I have some templates customized and some ports and devices disabled.

```
root@wb:~# wb-mcu-fw-updater update-all
2021-08-21 14:59:48,081 Will probe all devices defined in /etc/wb-mqtt-serial.conf
2021-08-21 14:59:51,601 Unhandled exception!
Traceback (most recent call last):
  File "/usr/bin/wb-mcu-fw-updater", line 117, in <module>
    func(args)
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 493, in update_all
    _update_all(force=args.force)
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 250, in _update_all
    alive, in_bootloader, dummy_records, too_old_devices = probe_all_devices(CONFIG['SERIAL_DRIVER_CONFIG_FNAME'])
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 241, in probe_all_devices
    db.save(modbus_connection.slaveid, modbus_connection.port, modbus_connection.get_fw_signature()) # old devices haven't fw_signatures
  File "/usr/lib/python3/dist-packages/wb_modbus/bindings.py", line 610, in get_fw_signature
    return self.read_string(self.COMMON_REGS_MAP['fw_signature'], self.FIRMWARE_SIGNATURE_LENGTH)
  File "/usr/lib/python3/dist-packages/wb_modbus/bindings.py", line 38, in wrapper
    raise thrown_exc
  File "/usr/lib/python3/dist-packages/wb_modbus/bindings.py", line 33, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/wb_modbus/bindings.py", line 413, in read_string
    ret = minimalmodbus._hexlify(self.device.read_string(addr, regs_lenght, 3))
  File "/usr/lib/python3/dist-packages/wb_modbus/minimalmodbus.py", line 755, in read_string
    payloadformat=_PAYLOADFORMAT_STRING,
  File "/usr/lib/python3/dist-packages/wb_modbus/minimalmodbus.py", line 1170, in _generic_command
    payload_from_slave = self._perform_command(functioncode, payload_to_slave)
  File "/usr/lib/python3/dist-packages/wb_modbus/minimalmodbus.py", line 1240, in _perform_command
    response = self._communicate(request, number_of_bytes_to_read)
  File "/usr/lib/python3/dist-packages/wb_modbus/minimalmodbus.py", line 1406, in _communicate
    raise NoResponseError("No communication with the instrument (no answer)")
wb_modbus.minimalmodbus.NoResponseError: No communication with the instrument (no answer)

```

`/etc/wb-mqtt-serial.conf`

```
{
  "debug" : false,
  "ports" : 
  [
    {
      "baud_rate" : 115200,
      "data_bits" : 8,
      "devices" : 
      [
        {
          "delay_ms" : 8,
          "device_type" : "WB-MR6C (home33)",
          "poll_interval" : 300,
          "slave_id" : "161"
        },
        {
          "delay_ms" : 8,
          "device_type" : "WB-MR6C (home33)",
          "slave_id" : "169"
        },
        {
          "delay_ms" : 8,
          "device_type" : "WB-MR6C (home33)",
          "poll_interval" : 300,
          "slave_id" : "172"
        },
        {
          "delay_ms" : 8,
          "device_type" : "WB-MR6C (home33)",
          "slave_id" : "177"
        },
        {
          "delay_ms" : 8,
          "device_type" : "WB-MR6C (home33)",
          "poll_interval" : 300,
          "slave_id" : "214"
        },
        {
          "device_type" : "WB-MRPS6",
          "slave_id" : "45"
        },
        {
          "device_type" : "WB-MRPS6",
          "slave_id" : "19"
        },
        {
          "device_type" : "WB-MRPS6",
          "enabled" : true,
          "slave_id" : "20"
        },
        {
          "device_type" : "WB-MRPS6",
          "enabled" : false,
          "slave_id" : "31"
        },
        {
          "device_type" : "WB-MWWWW-D",
          "slave_id" : "167"
        },
        {
          "device_type" : "WB-MWWWW-D",
          "enabled" : false,
          "slave_id" : "226"
        }
      ],
      "enabled" : true,
      "guard_interval_us" : 0,
      "parity" : "N",
      "path" : "/dev/ttyRS485-1",
      "poll_interval" : 3000,
      "response_timeout_ms" : 100,
      "stop_bits" : 2
    },
    {
      "baud_rate" : 115200,
      "data_bits" : 8,
      "devices" : 
      [
        {
          "delay_ms" : 10,
          "device_type" : "WB-MSW v.3 base",
          "slave_id" : 21
        },
        {
          "delay_ms" : 10,
          "device_type" : "WB-MSW v.3 base",
          "slave_id" : "18"
        }
      ],
      "enabled" : true,
      "parity" : "N",
      "path" : "/dev/ttyRS485-2",
      "poll_interval" : 2000,
      "stop_bits" : 2
    },
    {
      "baud_rate" : 115200,
      "data_bits" : 8,
      "devices" : 
      [
        {
          "device_type" : "WB-MAP3H fw2 (home33)",
          "setup" : 
          [
            {
              "address" : "0x1460",
              "title" : "CT L1 ratio",
              "value" : "2996"
            },
            {
              "address" : "0x1461",
              "title" : "CT L2 ratio",
              "value" : "2993"
            },
            {
              "address" : "0x1462",
              "title" : "CT L3 ratio",
              "value" : "2995"
            },
            {
              "address" : "0x1463",
              "title" : "Phi L1",
              "value" : "938"
            },
            {
              "address" : "0x1464",
              "title" : "Phi L2",
              "value" : "736"
            },
            {
              "address" : "0x1465",
              "title" : "Phi L3",
              "value" : "865"
            }
          ],
          "slave_id" : 74
        },
        {
          "channels" : 
          [
            {
              "device_type" : "channel 1",
              "name" : "Channel 1"
            },
            {
              "device_type" : "channel 2",
              "name" : "Channel 2"
            },
            {
              "device_type" : "channel 3",
              "name" : "Channel 3"
            },
            {
              "device_type" : "channel 4",
              "name" : "Channel 4"
            },
            {
              "device_type" : "channel 5",
              "name" : "Channel 5"
            },
            {
              "device_type" : "channel 6",
              "name" : "Channel 6"
            }
          ],
          "device_type" : "WB-MAP6S fw2",
          "setup" : 
          [
            {
              "address" : "0x1462",
              "title" : "ratio 1",
              "value" : "2995"
            },
            {
              "address" : "0x1461",
              "title" : "ratio 2",
              "value" : "2995"
            },
            {
              "address" : "0x1460",
              "title" : "ratio 3",
              "value" : "2993"
            },
            {
              "address" : "0x2462",
              "title" : "ratio 4",
              "value" : "2999"
            },
            {
              "address" : "0x2461",
              "title" : "ratio 5",
              "value" : "2998"
            },
            {
              "address" : "0x2460",
              "title" : "ratio 6",
              "value" : "2994"
            },
            {
              "address" : "0x1465",
              "title" : "phi 1",
              "value" : "763"
            },
            {
              "address" : "0x1464",
              "title" : "phi 2",
              "value" : "802"
            },
            {
              "address" : "0x1463",
              "title" : "phi 3",
              "value" : "646"
            },
            {
              "address" : "0x2465",
              "title" : "phi 4",
              "value" : "1071"
            },
            {
              "address" : "0x2464",
              "title" : "phi 5",
              "value" : "934"
            },
            {
              "address" : "0x2463",
              "title" : "phi 6",
              "value" : "679"
            }
          ],
          "slave_id" : 57
        }
      ],
      "enabled" : true,
      "parity" : "N",
      "path" : "/dev/ttyMOD1",
      "poll_interval" : 5000,
      "stop_bits" : 2
    },
    {
      "baud_rate" : 115200,
      "data_bits" : 8,
      "devices" : [],
      "enabled" : true,
      "parity" : "N",
      "path" : "/dev/ttyMOD2",
      "poll_interval" : 10,
      "stop_bits" : 2
    },
    {
      "baud_rate" : 9600,
      "data_bits" : 8,
      "devices" : [],
      "enabled" : false,
      "parity" : "N",
      "path" : "/dev/ttyMOD3",
      "poll_interval" : 10,
      "stop_bits" : 2
    }
  ]
}
```

**Comment by vdromanov** [comment]
приветствую!
хочется знать версию (apt policy wb-mcu-fw-updater)
