### ISSUE TITLE
deb-package fails, at first, to be build and then to be installed with unsatisfied dependencies

### ISSUE THREAD

**Issue by ashumkin** [wirenboard/wb-mcu-fw-updater#35]
In the [installation instructions](https://wirenboard.com/wiki/Wb-mcu-fw-updater#%D0%9E%D0%A1_Linux) is said:

> ОС Linux
> Для Debian-подобных операционных систем есть скрипт, который выполняет функции утилиты wb-mcu-fw-updater и использует wb-mcu-fw-flasher.
> 
> Подготовка комплекта:
> 
> Перейдите в репозиторий [wb-mcu-fw-updater](https://github.com/wirenboard/wb-mcu-fw-updater.git).
> Соберите deb-пакет по инструкции в репозитории.
> Установите утилиту [wb-mcu-fw-flasher](https://wirenboard.com/wiki/WB-MCU-Flasher).
> Установите собранный deb-пакет командами:
> apt update
> apt install ./<путь_до_собранного_пакета>.deb

First, the `dpkg-buildpackage -rfakeroot -us -uc` command fails becase `dh-python` package is not installed (OK, this is solved with `apt install dh-python` command.

After I've built a deb-packages , I've tried to install that packages
```
apt install ../wb-mcu-fw-updater_1.6.2_all.deb ../python3-wb-mcu-fw-updater_1.6.2_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wb-mcu-fw-updater' instead of '../wb-mcu-fw-updater_1.6.2_all.deb'
Note, selecting 'python3-wb-mcu-fw-updater' instead of '../python3-wb-mcu-fw-updater_1.6.2_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-wb-mcu-fw-updater : Depends: python3-mqttrpc (>= 1.1.2) but it is not installable
                             Recommends: wb-mqtt-serial (>= 2.73.0) but it is not installable
 wb-mcu-fw-updater : Depends: wb-release-info but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Ok,  I've removed `wb-release-info` from `debian/control` file and have rebuilt the packages.
Then I've tried to reinstall the packages. But I' got the almost the same error

but 
```
apt search python3-mqttrpc
Sorting... Done
Full Text Search... Done
```
searches nothing

I have Ubuntu 20.04 LTS.

What is `python3-mqttrpc` package? Where to get it? Google did not help. )

**Comment by evgeny-boger** [comment]
here it is: 

Source: https://github.com/wirenboard/python-mqtt-rpc
The deb package: https://deb.wirenboard.com/wb7/bullseye/pool/main/p/python-mqttrpc/python3-mqttrpc_1.1.3_all.deb

**Comment by ashumkin** [comment]
> here it is:

thank you!

also, after building and installation of its dependency https://github.com/wirenboard/json-rpc, the target deb finally have been installed.

But, unfortunately it does not work silently without `websockets=8.1` installed (https://github.com/beerfactory/hbmqtt/issues/239)

Ok, that's solved

but now
``` 
$ wb-mcu-fw-updater update-fw -a97 /dev/ttyACM0 
2022-11-05 16:09:52,950 Critical error in /usr/lib/wb-release file! Contact the support!
2022-11-05 16:09:52,951 Unhandled exception!
Traceback (most recent call last):
  File "/usr/bin/wb-mcu-fw-updater", line 325, in <module>
    update_monitor.fill_release_info()
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 77, in fill_release_info
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 74, in fill_release_info
    RELEASE_INFO = releases.parse_releases(releases_fname)
  File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/releases.py", line 26, in parse_releases
    with open(fname) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/wb-release'
2022-11-05 16:09:52,955 Haven't rights to write /var/lib/wb-mcu-fw-updater/devices.jsondb! Try with sudo
```

So, the dependency from `wb-release-info` (that I removed earlier) is "critical" )) (for now).
I guess, the code is needed to be patched )) to avoid that ))

P.S. actually the whole case is born from the need to use [WB-USB485](https://wirenboard.com/wiki/WB-USB485_v.1_Interface_Converter) on a laptop with the new devices for updating their firmwares before install them.
